#!/usr/bin/env python3
"""Deterministic host-side acceptance sender for the P4-NANO SDMMC test."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import serial


PAYLOAD = b"WRITE_TEST\n"
TX_HEX = PAYLOAD.hex()

STARTUP_MARKERS = (
    b"chip revision: v1.3",
    b"P4-NANO SD POWER CONFIG: PASS",
    b"P4-NANO SD HOST INIT: PASS",
    b"P4-NANO SD CARD INIT: PASS",
    b"P4-NANO SD CARD INFO: PASS",
    b"SD card: type=SD capacity=8068792320 bytes sector=512 bus_width=4 real_freq=20000 kHz",
    b"P4-NANO FAT MOUNT: PASS",
    b"P4-NANO FAT ROOT LIST: PASS",
    b"P4-NANO README READ: PASS",
    b"P4-NANO SD READ-ONLY RESULT: PASS",
    b"P4-NANO SD WRITE COMMAND READY",
    b"P4-NANO SAFE-OFF LED ENABLED",
    b"P4-NANO SAFE TO POWER OFF: YES",
)

TRANSACTION_MARKERS = (
    b"P4-NANO SAFE-OFF LED DISABLED",
    b"P4-NANO SAFE TO POWER OFF: NO",
    b"P4-NANO SD WRITE COMMAND ACCEPTED",
    b"P4-NANO SD WRITE TEST BEGIN",
    b"P4-NANO SD FILE CREATE: BEGIN",
    b"P4-NANO SD FILE CREATE: PASS",
    b"P4-NANO SD FILE WRITE: BEGIN",
    b"P4-NANO SD FILE WRITE: PASS bytes=4096",
    b"P4-NANO SD FILE READ: BEGIN",
    b"P4-NANO SD FILE READ: PASS bytes=4096",
    b"P4-NANO SD FILE VERIFY: PASS",
    b"P4-NANO SD FILE DELETE: BEGIN",
    b"P4-NANO SD FILE DELETE: PASS",
    b"P4-NANO SD WRITE TEST RESULT: PASS",
    b"P4-NANO SAFE-OFF LED ENABLED",
    b"P4-NANO SAFE TO POWER OFF: YES",
)

RESET_MARKERS = (
    b"ESP-ROM:esp32p4",
    b"rst:",
    b"ESP-IDF v5.5.4 2nd stage bootloader",
)


class TransactionCapture:
    """Validate only the ordered markers received after one TX operation."""

    def __init__(self) -> None:
        self.rx = bytearray()
        self.next_marker = 0
        self.scan_offset = 0
        self.result: str | None = None
        self.reason: str | None = None

    @property
    def complete(self) -> bool:
        return self.result == "PASS"

    def feed(self, chunk: bytes) -> None:
        if self.result is not None:
            return
        self.rx.extend(chunk)

        while self.result is None:
            events: list[tuple[int, str, bytes]] = []
            for marker in RESET_MARKERS:
                position = self.rx.find(marker, self.scan_offset)
                if position >= 0:
                    events.append((position, "RESET", marker))
            for marker in TRANSACTION_MARKERS:
                position = self.rx.find(marker, self.scan_offset)
                if position >= 0:
                    events.append((position, "MARKER", marker))
            if not events:
                return

            position, kind, marker = min(events, key=lambda event: event[0])
            self.scan_offset = position + len(marker)
            if kind == "RESET":
                self.result = "ABORTED BY RESET"
                self.reason = marker.decode("ascii", errors="replace")
                return

            expected = TRANSACTION_MARKERS[self.next_marker]
            if marker != expected:
                self.result = "FAIL"
                self.reason = (
                    f"out-of-order marker: got {marker.decode()}, "
                    f"expected {expected.decode()}"
                )
                return

            self.next_marker += 1
            if self.next_marker == len(TRANSACTION_MARKERS):
                self.result = "PASS"


def assert_self_test(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def run_self_test() -> None:
    stale = b"P4-NANO SD WRITE TEST RESULT: PASS\n"
    prefix = b"".join(TRANSACTION_MARKERS[:3])
    incomplete = b"".join(TRANSACTION_MARKERS[:-2]) + TRANSACTION_MARKERS[-2]
    full = b"".join(TRANSACTION_MARKERS)

    # A stale result is intentionally kept outside the post-TX capture.
    pre_tx = bytearray(stale)
    capture = TransactionCapture()
    capture.feed(prefix)
    assert_self_test(not capture.complete, "stale PASS incorrectly counted")
    assert_self_test(pre_tx == stale, "pre-TX fixture was unexpectedly consumed")

    capture = TransactionCapture()
    capture.feed(incomplete)
    assert_self_test(not capture.complete, "incomplete transaction counted")
    assert_self_test(capture.result is None, "incomplete transaction was not left pending")

    capture = TransactionCapture()
    for offset in range(0, len(full), 7):
        capture.feed(full[offset:offset + 7])
    assert_self_test(capture.complete, "full ordered transaction was not accepted")

    capture = TransactionCapture()
    capture.feed(b"".join(TRANSACTION_MARKERS[:2]) + b"ESP-ROM:esp32p4")
    assert_self_test(capture.result == "ABORTED BY RESET", "reset was not detected")

    print("acceptance_write.py self-test: PASS")


def open_serial_without_flow_control(port: str) -> serial.Serial:
    # Configure inactive control-line states before opening. No reset pulse is
    # generated by this helper; platform-specific open-time glitches remain
    # observable and are not silently treated as a cold boot.
    connection = serial.Serial(
        port=None,
        baudrate=115200,
        timeout=0.1,
        write_timeout=2.0,
        dsrdtr=False,
        rtscts=False,
    )
    connection.port = port
    connection.dtr = False
    connection.rts = False
    connection.open()
    return connection


def read_until_ready(connection: serial.Serial, timeout: float) -> bytearray:
    rx = bytearray()
    deadline = time.monotonic() + timeout
    ready_at: float | None = None
    while time.monotonic() < deadline:
        chunk = connection.read(256)
        if chunk:
            rx.extend(chunk)
            sys.stdout.buffer.write(chunk)
            sys.stdout.buffer.flush()
        if all(marker in rx for marker in STARTUP_MARKERS):
            if ready_at is None:
                ready_at = time.monotonic()
            if time.monotonic() - ready_at >= 3.0:
                return rx
        else:
            ready_at = None
    raise RuntimeError("required READ-ONLY/READY markers were not observed")


def run_transaction(connection: serial.Serial, timeout: float) -> TransactionCapture:
    connection.reset_input_buffer()
    capture = TransactionCapture()
    written = connection.write(PAYLOAD)
    connection.flush()
    print(f"\nHOST TX hex: {TX_HEX}", flush=True)
    print(f"HOST TX length: {written} bytes", flush=True)
    if written != len(PAYLOAD):
        capture.result = "FAIL"
        capture.reason = "short host TX"
        return capture

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline and capture.result is None:
        chunk = connection.read(256)
        if chunk:
            capture.feed(chunk)
            sys.stdout.buffer.write(chunk)
            sys.stdout.buffer.flush()
    if capture.result is None:
        capture.result = "TIMEOUT"
        capture.reason = "current transaction result not observed"
    return capture


def run_hardware(port: str) -> int:
    connection = open_serial_without_flow_control(port)
    try:
        read_until_ready(connection, timeout=30.0)
        capture = run_transaction(connection, timeout=15.0)
        print(f"\nHOST RESULT: {capture.result}", flush=True)
        if capture.reason:
            print(f"HOST REASON: {capture.reason}", flush=True)
        return 0 if capture.complete else 1
    finally:
        connection.close()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--port")
    args = parser.parse_args()
    if args.self_test:
        run_self_test()
        return 0
    if not args.port:
        parser.error("--port is required for hardware mode")
    return run_hardware(args.port)


if __name__ == "__main__":
    raise SystemExit(main())
