#include "np2_keyboard_input/np2_key_mapping.hpp"

namespace np2_keyboard_input::mapping {

std::optional<FrontendKeyId> to_frontend_key_id(Key key) noexcept
{
    switch (key) {
    case Key::Escape:
        return FrontendKeyId::Escape;
    case Key::Digit1:
        return FrontendKeyId::Digit1;
    case Key::Digit2:
        return FrontendKeyId::Digit2;
    case Key::Digit3:
        return FrontendKeyId::Digit3;
    case Key::Digit4:
        return FrontendKeyId::Digit4;
    case Key::Digit5:
        return FrontendKeyId::Digit5;
    case Key::Digit6:
        return FrontendKeyId::Digit6;
    case Key::Digit7:
        return FrontendKeyId::Digit7;
    case Key::Digit8:
        return FrontendKeyId::Digit8;
    case Key::Digit9:
        return FrontendKeyId::Digit9;
    case Key::Digit0:
        return FrontendKeyId::Digit0;
    case Key::Minus:
        return FrontendKeyId::Minus;
    case Key::Circumflex:
        return FrontendKeyId::Circumflex;
    case Key::Yen:
        return FrontendKeyId::Yen;
    case Key::Backspace:
        return FrontendKeyId::Backspace;
    case Key::Tab:
        return FrontendKeyId::Tab;
    case Key::Q:
        return FrontendKeyId::Q;
    case Key::W:
        return FrontendKeyId::W;
    case Key::E:
        return FrontendKeyId::E;
    case Key::R:
        return FrontendKeyId::R;
    case Key::T:
        return FrontendKeyId::T;
    case Key::Y:
        return FrontendKeyId::Y;
    case Key::U:
        return FrontendKeyId::U;
    case Key::I:
        return FrontendKeyId::I;
    case Key::O:
        return FrontendKeyId::O;
    case Key::P:
        return FrontendKeyId::P;
    case Key::At:
        return FrontendKeyId::At;
    case Key::LeftBracket:
        return FrontendKeyId::LeftBracket;
    case Key::Enter:
    case Key::KeypadEnter:
        return FrontendKeyId::Enter;
    case Key::A:
        return FrontendKeyId::A;
    case Key::S:
        return FrontendKeyId::S;
    case Key::D:
        return FrontendKeyId::D;
    case Key::F:
        return FrontendKeyId::F;
    case Key::G:
        return FrontendKeyId::G;
    case Key::H:
        return FrontendKeyId::H;
    case Key::J:
        return FrontendKeyId::J;
    case Key::K:
        return FrontendKeyId::K;
    case Key::L:
        return FrontendKeyId::L;
    case Key::Semicolon:
        return FrontendKeyId::Semicolon;
    case Key::Colon:
        return FrontendKeyId::Colon;
    case Key::RightBracket:
        return FrontendKeyId::RightBracket;
    case Key::Z:
        return FrontendKeyId::Z;
    case Key::X:
        return FrontendKeyId::X;
    case Key::C:
        return FrontendKeyId::C;
    case Key::V:
        return FrontendKeyId::V;
    case Key::B:
        return FrontendKeyId::B;
    case Key::N:
        return FrontendKeyId::N;
    case Key::M:
        return FrontendKeyId::M;
    case Key::Comma:
        return FrontendKeyId::Comma;
    case Key::Period:
        return FrontendKeyId::Period;
    case Key::Slash:
        return FrontendKeyId::Slash;
    case Key::Underscore:
        return FrontendKeyId::Underscore;
    case Key::Space:
        return FrontendKeyId::Space;
    case Key::Xfer:
        return FrontendKeyId::Xfer;
    case Key::RollUp:
        return FrontendKeyId::RollUp;
    case Key::RollDown:
        return FrontendKeyId::RollDown;
    case Key::Insert:
        return FrontendKeyId::Insert;
    case Key::Delete:
        return FrontendKeyId::Delete;
    case Key::Up:
        return FrontendKeyId::Up;
    case Key::Left:
        return FrontendKeyId::Left;
    case Key::Right:
        return FrontendKeyId::Right;
    case Key::Down:
        return FrontendKeyId::Down;
    case Key::HomeClear:
        return FrontendKeyId::HomeClear;
    case Key::Help:
        return FrontendKeyId::Help;
    case Key::KeypadMinus:
        return FrontendKeyId::KeypadMinus;
    case Key::KeypadDivide:
        return FrontendKeyId::KeypadDivide;
    case Key::Keypad7:
        return FrontendKeyId::Keypad7;
    case Key::Keypad8:
        return FrontendKeyId::Keypad8;
    case Key::Keypad9:
        return FrontendKeyId::Keypad9;
    case Key::KeypadMultiply:
        return FrontendKeyId::KeypadMultiply;
    case Key::Keypad4:
        return FrontendKeyId::Keypad4;
    case Key::Keypad5:
        return FrontendKeyId::Keypad5;
    case Key::Keypad6:
        return FrontendKeyId::Keypad6;
    case Key::KeypadPlus:
        return FrontendKeyId::KeypadPlus;
    case Key::Keypad1:
        return FrontendKeyId::Keypad1;
    case Key::Keypad2:
        return FrontendKeyId::Keypad2;
    case Key::Keypad3:
        return FrontendKeyId::Keypad3;
    case Key::KeypadEquals:
        return FrontendKeyId::KeypadEquals;
    case Key::Keypad0:
        return FrontendKeyId::Keypad0;
    case Key::KeypadComma:
        return FrontendKeyId::KeypadComma;
    case Key::KeypadPeriod:
        return FrontendKeyId::KeypadPeriod;
    case Key::Nfer:
        return FrontendKeyId::Nfer;
    case Key::F1:
        return FrontendKeyId::F1;
    case Key::F2:
        return FrontendKeyId::F2;
    case Key::F3:
        return FrontendKeyId::F3;
    case Key::F4:
        return FrontendKeyId::F4;
    case Key::F5:
        return FrontendKeyId::F5;
    case Key::F6:
        return FrontendKeyId::F6;
    case Key::F7:
        return FrontendKeyId::F7;
    case Key::F8:
        return FrontendKeyId::F8;
    case Key::F9:
        return FrontendKeyId::F9;
    case Key::F10:
        return FrontendKeyId::F10;
    case Key::LeftShift:
        return FrontendKeyId::LeftShift;
    case Key::CapsLock:
        return FrontendKeyId::CapsLock;
    case Key::Kana:
        return FrontendKeyId::Kana;
    case Key::Grph:
        return FrontendKeyId::Grph;
    case Key::Control:
        return FrontendKeyId::Control;
    case Key::RightShift:
        return FrontendKeyId::RightShift;
    case Key::Stop:
        return FrontendKeyId::Stop;
    case Key::Copy:
        return FrontendKeyId::Copy;
    case Key::Unknown:
    case Key::Count:
        return std::nullopt;
    }
    return std::nullopt;
}

} // namespace np2_keyboard_input::mapping
